version: '3.8'
services:

  universidades-db:
    image: postgres:13
    container_name: Universidad
    restart: always
    environment:
      POSTGRES_DB: Universidad
      POSTGRES_USER: usuario1
      POSTGRES_PASSWORD: contraseña
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  universidades-api:
    image: johnnys567/universidades-api:1.0
    container_name: universidades-api
    depends_on:
      - universidades-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://universidades-db:5432/Universidad
      SPRING_DATASOURCE_USERNAME: usuario1
      SPRING_DATASOURCE_PASSWORD: contraseña

volumes:
  pgdata:
