apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: universidades-db
  labels:
    app: universidades-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: universidades-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: universidades-db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: Universidad
            - name: POSTGRES_USER
              value: usuario1
            - name: POSTGRES_PASSWORD
              value: contraseña
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
            - mountPath: /docker-entrypoint-initdb.d/
              name: init-sql-volume
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
        - name: init-sql-volume
          configMap:
            name: initdb-config
---
apiVersion: v1
kind: Service
metadata:
  name: universidades-db
spec:
  selector:
    app: universidades-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
